### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by xandros6** [tonyp7/esp32-wifi-manager#75]
Hi, 
first, thanks for all the great work. I will try to contribute to its maintenance and evolution.
I have one question regarding security after the device is correctly registered to WIF: the configuration page is visible using the assigned IP. 
This is good to change the STA parameters, however, the page is accessible without protection, so a generic user can discover the device IP and change the WIFI configuration.
How is (if actually) possible to protect the page with user / pwd?

Thanks.

**Comment by tonyp7** [comment]
Hello @xandros6 ,

You are right, but this is by design. The wifi manager must remain as simple as possible. Adding a basic HTTP AUTH could work but would make the whole experience less seemless. 

This intended purpose of this is just to get an IP from your local LAN for your embedded system without hardcoding it and forget about it.

If you need to deploy your project where the device page needs to be protected, this might not be the software you need.
